# -*- coding: utf-8 -*-
"""analyzer.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QeuLaMjBwulIhoBHLF5dz72PyuK94Jx_
"""

from collections import defaultdict

def read_expenses():
    # This is a placeholder for your actual expense data.
    # In a real scenario, this function would read from a file, database, etc.
    return [
        ['2023-01-01', 'Food', '50.00'],
        ['2023-01-01', 'Transport', '15.50'],
        ['2023-01-02', 'Food', '30.25'],
        ['2023-01-02', 'Utilities', '120.00'],
        ['2023-01-03', 'Entertainment', '75.00'],
        ['2023-01-03', 'Food', '40.00'],
        ['2023-01-04', 'Transport', '20.00']
    ]

def total_spent():
    expenses = read_expenses()
    total = sum(float(exp[2]) for exp in expenses)
    print(f"\nTotal Money Spent: ₹{total}\n")


def category_wise_summary():
    expenses = read_expenses()
    categories = defaultdict(float)

    for exp in expenses:
        categories[exp[1]] += float(exp[2])

    print("\n--- Category Wise Summary ---")
    for cat, amt in categories.items():
        print(f"{cat}: ₹{amt}")
    print("-----------------------------\n")


def highest_lowest_expense():
    expenses = read_expenses()

    if not expenses:
        print("No expenses found.\n")
        return

    highest = max(expenses, key=lambda x: float(x[2]))
    lowest = min(expenses, key=lambda x: float(x[2]))

    print("\nHighest Expense:")
    print(f"{highest[1]} - ₹{highest[2]} on {highest[0]}\n")

    print("Lowest Expense:")
    print(f"{lowest[1]} - ₹{lowest[2]} on {lowest[0]}\n")

