# -*- coding: utf-8 -*-
"""data.csv

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10DE4jROlxtDgHz8-eny40KNckWW1uJ9n
"""

open("data.csv", "w").write("")