# -*- coding: utf-8 -*-
"""expense_manager.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ej6GpW9k_I4nfT3JRERmWep6pCgg71of
"""

import os

def save_expense(date, category, amount, note):
    with open("data.csv", "a") as f:
        f.write(f"{date},{category},{amount},{note}\n")

def read_expenses():
    if not os.path.exists("data.csv"):
        return []
    expenses = []
    with open("data.csv", "r") as f:
        for line in f:
            expenses.append(line.strip().split(","))
    return expenses

def add_expense():
    date = input("Enter date (DD-MM-YYYY): ")
    category = input("Enter category (Food/Travel/Shopping/etc): ")
    amount = input("Enter amount: ")
    note = input("Enter note (optional): ")

    save_expense(date, category, amount, note)
    print("Expense added successfully!\n")


def view_expenses():
    expenses = read_expenses()

    if not expenses:
        print("No expenses recorded yet.\n")
        return

    print("\n------ All Expenses ------")
    for i, exp in enumerate(expenses):
        print(f"{i+1}. Date: {exp[0]}, Category: {exp[1]}, Amount: {exp[2]}, Note: {exp[3]}")
    print("--------------------------\n")


def delete_expense():
    expenses = read_expenses()

    if not expenses:
        print("No expenses to delete.\n")
        return

    view_expenses()
    try:
        index = int(input("Enter expense number to delete: ")) - 1
    except ValueError:
        print("Invalid input. Please enter a number.\n")
        return

    if 0 <= index < len(expenses):
        del expenses[index]
        # rewrite file
        with open("data.csv", "w") as f:
            for e in expenses:
                f.write(",".join(e) + "\n")
        print("Expense deleted successfully!\n")
    else:
        print("Invalid choice.\n")

