# -*- coding: utf-8 -*-
"""main.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RzB9mq9eZjfaZSG7loRnTacWycPCBfBU
"""

# Placeholder functions for expense_manager
def add_expense():
    print("Add expense function (placeholder)")

def view_expenses():
    print("View expenses function (placeholder)")

def delete_expense():
    print("Delete expense function (placeholder)")

# Placeholder functions for analyzer
def total_spent():
    print("Total spent function (placeholder)")

def category_wise_summary():
    print("Category-wise summary function (placeholder)")

def highest_lowest_expense():
    print("Highest & lowest expense function (placeholder)")

def menu():
    while True:
        print("=== Student Expense Tracker ===")
        print("1. Add Expense")
        print("2. View Expenses")
        print("3. Delete Expense")
        print("4. Total Spent")
        print("5. Category-wise Summary")
        print("6. Highest & Lowest Expense")
        print("7. Exit")

        choice = input("Enter choice: ")

        if choice == "1":
            add_expense()
        elif choice == "2":
            view_expenses()
        elif choice == "3":
            delete_expense()
        elif choice == "4":
            total_spent()
        elif choice == "5":
            category_wise_summary()
        elif choice == "6":
            highest_lowest_expense()
        elif choice == "7":
            print("Goodbye!")
            break
        else:
            print("Invalid choice!\n")